services:
  postgres:
    image: postgres:15-alpine
    container_name: cinema_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: cinema_db
      POSTGRES_USER: cinema_user
      POSTGRES_PASSWORD: cinema_password
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    networks:
      - cinema_network

networks:
  cinema_network:
    driver: bridge
